src/Controllers/DynamicController.cs
using GovUk.Education.SearchAndCompare.Domain.Client;
using GovUk.Education.SearchAndCompare.UI.Services;
using Microsoft.ApplicationInsights;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GovUk.Education.SearchAndCompare.UI.Controllers
{

    public class DynamicController : Controller
    {
        private readonly ISearchAndCompareApi _api;

        private readonly IGeocoder _geocoder;

        private readonly TelemetryClient _telemetryClient;

        public DynamicController(ISearchAndCompareApi api, IGeocoder geocoder, TelemetryClient telemetryClient)
        {
            _api = api;
            _geocoder = geocoder;
            _telemetryClient = telemetryClient;
        }

        [HttpGet("/dynamic/providersuggest")]
        public JsonResult ProviderSuggest(string query)
        {
            var res = _api.GetProviderSuggestions(query);
            return Json(res.Select(x => new { name = x.Name, providerCode = x.ProviderCode }).ToList());
        }

        [HttpGet("/dynamic/locationsuggest")]
        public async Task<JsonResult> LocationSuggest(string query)
        {
            IEnumerable<string> res = new List<string>();

            try
            {
                res = await _geocoder.SuggestLocationsAsync(query);
            }
            catch (Exception ex)
            {
                _telemetryClient.TrackException(ex);
            }

            return Json(res.Count() > 5 ? res.Take(5) : res);
        }
    }
}

src/Controllers/FilterController.cs
using GovUk.Education.SearchAndCompare.Domain.Client;
using GovUk.Education.SearchAndCompare.Domain.Filters.Enums;
using GovUk.Education.SearchAndCompare.Domain.Models;
using GovUk.Education.SearchAndCompare.Services;
using GovUk.Education.SearchAndCompare.UI.Filters;
using GovUk.Education.SearchAndCompare.UI.Filters.Enums;
using GovUk.Education.SearchAndCompare.UI.Services;
using GovUk.Education.SearchAndCompare.UI.Utils;
using GovUk.Education.SearchAndCompare.UI.ViewModels;
using Microsoft.ApplicationInsights;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace GovUk.Education.SearchAndCompare.UI.Controllers
{

    public class FilterController : Controller
    {
        private readonly ISearchAndCompareApi _api;

        private readonly IGeocoder _geocoder;

        private readonly TelemetryClient _telemetryClient;

        private readonly GoogleAnalyticsClient _gaClient;

        public FilterController(ISearchAndCompareApi api, IGeocoder geocoder, TelemetryClient telemetryClient, GoogleAnalyticsClient gaClient)
        {
            _api = api;
            _geocoder = geocoder;
            _telemetryClient = telemetryClient;
            _gaClient = gaClient;
        }

        [HttpGet("results/filter/subject")]
        [ActionName("Subject")]
        public IActionResult SubjectGet(ResultsFilter filter)
        {
            var subjectAreas = _api.GetSubjectAreas();

            var viewModel = new SubjectFilterViewModel
            {
                SubjectAreas = subjectAreas,
                FilterModel = filter
            };

            ViewBag.Errors = TempData.Get<ErrorViewModel>("Errors");

            return View("Subject", viewModel);
        }

        [HttpPost("results/filter/subject")]
        [ActionName("Subject")]
        public IActionResult SubjectPost(ResultsFilter filter)
        {
            filter.page = null;

            var isInWizard = ViewBag.IsInWizard == true;
            if (!filter.SelectedSubjects.Any() && !filter.senCourses)
            {
                TempData.Put("Errors", new ErrorViewModel("subjects", "Please choose at least one subject", null, Url.Action("Subject")));
                return RedirectToAction(isInWizard ? "SubjectWizard" : "Subject", filter.ToRouteValues());
            }

            return RedirectToAction("Index", "Results", filter.ToRouteValues());
        }

        [HttpGet("start/subject")]
        [ActionName("SubjectWizard")]
        public IActionResult SubjectWizardGet(ResultsFilter filter)
        {
            ViewBag.IsInWizard = true;
            return SubjectGet(filter);
        }

        [HttpPost("start/subject")]
        [ActionName("SubjectWizard")]
        public IActionResult SubjectWizardPost(ResultsFilter filter)
        {
            ViewBag.IsInWizard = true;
            return SubjectPost(filter);
        }

        private IActionResult FullTextPost(ResultsFilter filter)
        {
            filter = filter.WithoutLocation();
            var queryIsEmpty = string.IsNullOrWhiteSpace(filter.query);

            if (queryIsEmpty)
            {
                TempData.Put("Errors", new ErrorViewModel("query", "Training provider", "Please enter the name of a training provider", Url.Action("Location")));
                return RedirectToAction("Location", filter.ToRouteValues());
            }

            var suggestions = _api.GetProviderSuggestions(filter.query);
            var noSuggestions = suggestions.Count == 0;

            // Note: this is the same block of code as the above. It's repeated because hoisting the logic for
            // the _api.GetProviderSuggestions call would make it call needlessly on queries which are empty.
            if (noSuggestions)
            {
                TempData.Put("Errors", new ErrorViewModel("query", "Training provider", "Please enter the name of a training provider", Url.Action("Location")));
                return RedirectToAction("Location", filter.ToRouteValues());
            }

            var queryIsExactMatch = suggestions.Any(x => x.Name.Equals(filter.query, StringComparison.InvariantCultureIgnoreCase));

            if (!queryIsExactMatch)
            {
                TempData.Put("Suggestions", suggestions);
                return RedirectToAction("Provider", filter.ToRouteValues());
            }

            return RedirectToAction("Index", "Results", filter.ToRouteValues());
        }


        [HttpGet("results/filter/location")]
        [ActionName("LocationGet")]
        public IActionResult LocationGet(ResultsFilter filter)
        {
            var viewModel = new LocationFilterViewModel
            {
                FilterModel = filter
            };
            var errors = TempData.Get<ErrorViewModel>("Errors");
            if (errors != null && errors.AppliesToUrl(Url.Action("Location")))
            {
                viewModel.Errors = errors;
            }

            return View("Location", viewModel);
        }

        [HttpPost("results/filter/location")]
        [ActionName("Location")]
        public async Task<IActionResult> LocationPost(ResultsFilter filter)
        {
            filter.page = null;

            if (filter.LocationOption == LocationOption.Specific)
            {
                return FullTextPost(filter);
            }

            var isInWizard = ViewBag.IsInWizard == true;
            filter.query = null;

            if (filter.LocationOption == LocationOption.Unset)
            {
                TempData.Put("Errors", new ErrorViewModel("l", "Please choose an option", null, Url.Action("Location")));
                return RedirectToAction(isInWizard ? "LocationWizard" : "Location", filter.WithoutLocation().ToRouteValues());
            }

            if (filter.LocationOption == LocationOption.No)
            {
                return isInWizard
                    ? RedirectToAction("SubjectWizard", filter.WithoutLocation().ToRouteValues())
                    : RedirectToAction("Index", "Results", filter.WithoutLocation().ToRouteValues());
            }

            if (string.IsNullOrWhiteSpace(filter.lq))
            {
                TempData.Put("Errors", new ErrorViewModel("lq", "Postcode, town or city", "Please enter a postcode, city or town in England", Url.Action("Location")));
                return RedirectToAction(isInWizard ? "LocationWizard" : "Location", filter.ToRouteValues());
            }

            var coords = await ResolveAddressAsync(filter.lq);
            if (coords == null)
            {
                TempData.Put("Errors", new ErrorViewModel("lq", "Postcode, town or city", "We couldn't find this location, please check your input and try again.", Url.Action("Location")));

                return RedirectToAction(isInWizard ? "LocationWizard" : "Location", filter.ToRouteValues());
            }
            else
            {
                filter.lat = coords.Latitude;
                filter.lng = coords.Longitude;
                filter.loc = coords.FormattedLocation;
                filter.page = null;
                filter.sortby = (int)SortByOption.Distance;

                var cid = Request.Cookies.TryGetValue("_gid", out string gid) ? gid : "";

                _gaClient.TrackEvent(cid, "Form: Location", "Selected Granularity", coords.Granularity);
                _gaClient.TrackEvent(cid, "Form: Location", "Selected Region", coords.Region);
            }

            return isInWizard
                ? RedirectToAction("SubjectWizard", filter.ToRouteValues())
                : RedirectToAction("Index", "Results", filter.ToRouteValues());
        }

        [HttpGet("/")]
        [ActionName("LocationWizard")]
        public IActionResult LocationWizardGet(ResultsFilter filter)
        {
            ViewBag.IsInWizard = true;
            //filter.qualification = filter.qualification.Any() ? filter.qualification : new List<QualificationOption> { QualificationOption.QtsOnly, QualificationOption.PgdePgceWithQts, QualificationOption.Other };
            filter.qualifications = !string.IsNullOrWhiteSpace(filter.qualifications) ? filter.qualifications : string.Join(",", Enum.GetNames(typeof(QualificationOption)));

            return LocationGet(filter);
        }

        [HttpPost("/")]
        [ActionName("LocationWizard")]
        public async Task<IActionResult> LocationWizardPost(ResultsFilter filter)
        {
            ViewBag.IsInWizard = true;
            return await LocationPost(filter);
        }

        [HttpGet("results/filter/funding")]
        public IActionResult Funding(ResultsFilter filter)
        {
            ViewBag.Errors = TempData.Get<ErrorViewModel>("Errors") ?? new ErrorViewModel();
            return View("Funding", filter);
        }

        [HttpPost("results/filter/funding")]
        public IActionResult Funding(bool? applyFilter, bool includeBursary, bool includeScholarship, bool includeSalary, ResultsFilter filter)
        {
            filter.page = null;

            if (!applyFilter.HasValue)
            {
                TempData.Put("Errors", new ErrorViewModel("applyFilter", "Please choose an option", null, Url.Action("Funding")));
                return RedirectToAction("Funding", filter.ToRouteValues());
            }

            else if (applyFilter == true && !includeBursary && !includeScholarship && !includeSalary)
            {
                TempData.Put("Errors", new ErrorViewModel("funding", "Funding options", "Please choose at least one funding option", Url.Action("Funding")));
                return RedirectToAction("Funding", filter.ToRouteValues());
            }
            else if (applyFilter == true)
            {
                filter.SelectedFunding = FundingOption.AnyFunding;
                if (!includeBursary) filter.SelectedFunding = filter.SelectedFunding & ~FundingOption.Bursary;

src/Views/Filter/Funding.cshtml
@model ResultsFilter

@{
  ViewBag.Title = $"Find courses that pay a salary";
  var errors = ViewBag.Errors as ErrorViewModel;
}

<div class="govuk-width-container">
  @await Html.PartialAsync("Back", new BackLinkViewModel {
    Href = Url.Action("Index", "Results", Model.ToRouteValues()),
    Title = "Back to search results"
  })
</div>

<main class="govuk-main-wrapper" id="main-content" role="main">
  <div class="govuk-width-container">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-full">
        @await Html.PartialAsync("Error", errors)
      </div>
    </div>

    <form action='@Url.Action("Funding", "Filter", Model.ToRouteValues())' method="POST" data-ga-event-form="Salary">
      <fieldset role="radiogroup" aria-required="true" class="govuk-fieldset">
        <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
          <h1 class="govuk-heading-xl">Find courses that pay a salary</h1>
        </legend>
        <div class="govuk-grid-row">
          <div class="govuk-grid-column-two-thirds">
            <p class="govuk-body">
              On a salaried course you’ll be paid and taxed as an unqualified teacher. The salary awarded will differ between schools – you should check the salary with the school before you apply.
            </p>
            <p class="govuk-body">
              Salaried courses are not eligible for bursaries, scholarships or student finance. There are usually no course fees to pay.
            </p>
            <div class="govuk-form-group @(errors.HasError("applyFilter") ? "govuk-form-group--error" : "")" id="applyFilter-container">
              <div class="govuk-radios" data-module="radios">
                <div class="govuk-radios__item">
                  <input id="applyFilter-all" class="govuk-radios__input" type="radio" name="applyFilter" value="false" checked="@(Model.SelectedFunding == FundingOption.All)" data-ga-event-form-input="All courses with/without a salary">
                  <label for="applyFilter-all" class="govuk-label govuk-radios__label">
                    All courses (with or without a salary)
                  </label>
                </div>
                <div class="govuk-radios__item">
                  <input id="applyFilter-some" class="govuk-radios__input" type="radio" name="applyFilter" value="true" checked="@(errors.HasError("funding ") || (Model.SelectedFunding != null && Model.SelectedFunding != FundingOption.All))" data-ga-event-form-input="Only courses with a salary">
                  <label for="applyFilter-some" class="govuk-label govuk-radios__label">
                    Only courses that come with a salary
                  </label>
                </div>
              </div>
              <input type="hidden" name="includeBursary" value="false">
              <input type="hidden" name="includeScholarship" value="false">
              <input type="hidden" name="includeSalary" value="true">
            </div>
          </div>
        </div>
      </fieldset>
      <div class="govuk-form-group">
        <input class="govuk-button" type="submit" value="Find courses">
      </div>
    </form>
  </div>
</main>

src/Views/Filter/Location.cshtml
@model LocationFilterViewModel

@{
  ViewBag.Title = $"Find courses by location or by training provider";
  var isInWizard = ViewBag.IsInWizard == true;
  var selectedRadius = (Model.FilterModel.rad.HasValue) ? Model.FilterModel.rad : (int)RadiusOption.TwentyMiles;
}

@if (!isInWizard)
{
  <div class="govuk-width-container">
    @await Html.PartialAsync("Back", new BackLinkViewModel { Href = Url.Action("Index", "Results", Model.FilterModel.ToRouteValues()), Title = "Back to search results" })
  </div>
}

<main class="govuk-main-wrapper" id="main-content" role="main">
  <div class="govuk-width-container">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        @await Html.PartialAsync("Error", Model.Errors)

        <form action='@Url.Action(isInWizard ? "LocationWizard" : "Location", "Filter", Model.FilterModel.ToRouteValues())' method="POST" data-ga-event-form="Location">
          <fieldset role="radiogroup" aria-required="true" class="govuk-fieldset">
            <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
              <h1 class="govuk-heading-xl">Find courses by location or by training provider</h1>
            </legend>

            <div class="govuk-form-group @(Model.Errors.HasError(" l ") ? "govuk-form-group--error" : " ")" id="l-container">

              @if (@Model.Errors.HasError("l")) {
                <span class="govuk-error-message">@Model.Errors.GetError("l").Message</span>
              }

              <div class="govuk-radios" data-module="radios">
                <div class="govuk-radios__item">
                  <input id="location-Set" class="govuk-radios__input" type="radio" name="l" value="@((int)LocationOption.Yes)" checked="@(Model.FilterModel.LocationOption == LocationOption.Yes)" data-aria-controls="lq-container" data-ga-event-form-input="By postcode/city">
                  <label for="location-Set" class="govuk-label govuk-radios__label">
                    By postcode, town or city
                  </label>
                </div>

                <div class="govuk-radios__conditional govuk-radios__conditional--hidden @(Model.Errors.HasError(" lq ") ? "form-group---error " : " ")" id="lq-container">
                  <div class="govuk-form-group">
                    <label class="govuk-label" for="location">
                      Postcode, town or city
                      @if (@Model.Errors.HasError("lq")) {
                        <span class="govuk-error-message">@Model.Errors.GetError("lq").Message</span>
                      }
                    </label>
                    <input class="govuk-input" data-url="@Url.Action("LocationSuggest", "Dynamic")" name="lq" type="text" id="location" value="@Model.FilterModel.lq">
                    <div id="location-autocomplete"></div>
                  </div>
                  <div class="govuk-form-group">
                    <label class="govuk-label" for="radius">Within</label>
                    <select class="govuk-select govuk-!-width-one-half" id="radius" name="rad">
                      @foreach(int option in Enum.GetValues(typeof(RadiusOption)))
                        {
                          if (option == selectedRadius) {
                            <option value="@(option)" selected="selected" >@(option) miles</option>
                          }
                          else
                          {
                            <option value="@(option)" >@(option) miles</option>
                          }
                        }
                    </select>
                  </div>
                </div>

                <div class="govuk-radios__item">
                  <input id="location-Unset" class="govuk-radios__input" type="radio" name="l" value="@((int)LocationOption.No)" checked="@(Model.FilterModel.LocationOption == LocationOption.No)" data-ga-event-form-input="Across England">
                  <label for="location-Unset" class="govuk-label govuk-radios__label">Across England</label>
                </div>

                <div class="govuk-radios__divider">or</div>

                <div class="govuk-radios__item">
                  <input id="location-Specific" class="govuk-radios__input" type="radio" name="l" value="@((int)LocationOption.Specific)" checked="@(Model.FilterModel.LocationOption == LocationOption.Specific)" data-aria-controls="query-container" data-ga-event-form-input="By school/provider">
                  <label for="location-Specific" class="govuk-label govuk-radios__label">
                    By school, university or other training provider
                  </label>
                </div>

                <div class="govuk-radios__conditional govuk-radios__conditional--hidden @(Model.Errors.HasError(" query ") ? "form-group--error " : " ")" id="query-container" data-module="track-no-provider-results">
                  <div class="form-group">
                    <label class="govuk-label" for="provider">
                      School, university or other training provider
                      @if (@Model.Errors.HasError("query")) {
                        <span class="govuk-error-message">@Model.Errors.GetError("query").Message</span>
                      }
                    </label>
                    <span class="govuk-hint">Enter the name or provider code</span>
                    <input class="govuk-input" data-url="@Url.Action("ProviderSuggest", "Dynamic")" name="query" type="text" id="provider" value="@Model.FilterModel.query">
                    <div id="provider-autocomplete"></div>
                  </div>
                </div>
              </div>
            </div>
          </fieldset>

          <div class="govuk-form-group">
            <input class="govuk-button" type="submit" value="@(isInWizard ? "Continue" : "Find courses")">
          </div>
        </form>
      </div>
    </div>
  </div>
</main>

src/Views/Filter/Provider.cshtml
@model ResultsFilter

@{
  ViewBag.Title = $"Pick a provider";
  var suggestions = ViewBag.suggestions;
}

<div class="govuk-width-container">
  @await Html.PartialAsync("Back", new BackLinkViewModel {
    Href = Url.Action("LocationWizard", "Filter", Model.ToRouteValues()),
    Title = "Back"
  })
</div>

<main class="govuk-main-wrapper" id="main-content" role="main">
  <div class="govuk-width-container">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
          <h1 class="govuk-heading-xl">Pick a provider</h1>
        </legend>

        <p>You searched for ‘@Model.query’.</p>

        <p>We found these providers which matched your search:</p>

        <ul class="govuk-list govuk-list--bullet">
          @foreach (var suggestion in suggestions)
          {
            <li><a class="govuk-link" href="@Url.Action("Index", "Results", RoutingUtil.Combine(Model.ToRouteValues(), new { query = @suggestion.Name }))">@suggestion.Name (@suggestion.ProviderCode)</a></li>
          }
        </ul>

        <hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">

        <details class="govuk-details">
          <summary class="govuk-details__summary">
            <span class="govuk-details__summary-text">Try another provider</span>
          </summary>
          <div class="govuk-details__text">
            <form action='@Url.Action("Location", "Filter", Model.ToRouteValues())' method="POST" data-ga-event-form="Provider">
              <fieldset aria-required="true" class="govuk-fieldset">
                <div class="govuk-form-group">
                  <label class="govuk-label" for="query">
                    <strong>School, university or other training provider</strong>
                    <span class="govuk-hint govuk-!-margin-bottom-0">Enter the name or provider code</span>
                  </label>
                  <input class="govuk-input" data-url="@Url.Action("ProviderSuggest", "Dynamic")" name="query" type="text" id="query" value="@Model.query">
                  <div id="provider-autocomplete"></div>
                </div>
              </fieldset>

              <input class="govuk-button govuk-!-margin-bottom-0" type="submit" value="Search again">
            </form>
          </div>
        </details>
      </div>
    </div>
  </div>
</main>

src/Views/Filter/Qualification.cshtml
@model ResultsFilter

@{
  ViewBag.Title = $"Filter by qualification";
}

<div class="govuk-width-container">
  @await Html.PartialAsync("Back", new BackLinkViewModel { Href = Url.Action("Index", "Results", Model.ToRouteValues()), Title = "Back to search results"})
</div>

<main class="govuk-main-wrapper" id="main-content" role="main">
  <div class="govuk-width-container">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <form action='@Url.Action("Qualification", "Filter", Model.ToRouteValues())' method="POST" data-ga-event-form="Qualification">
          <fieldset role="radiogroup" aria-required="true" class="govuk-fieldset">
            <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
              <h1 class="govuk-heading-xl">What you will get</h1>
            </legend>

            <div class="govuk-form-group">
              <div class="govuk-checkboxes">
                <div class="govuk-checkboxes__item">
                  <input id="applyFilter-qts-only" class="govuk-checkboxes__input" type="checkbox" name="qualification" value="@QualificationOption.QtsOnly" checked="@Model.qualifications.Contains(Enum.GetName(typeof(QualificationOption), QualificationOption.QtsOnly))" data-ga-event-form-input="QTS only">
                  <label for="applyFilter-qts-only" class="govuk-label govuk-checkboxes__label">
                    <span class="govuk-!-font-weight-bold govuk-!-margin-bottom-2 govuk-!-display-block">
                      QTS only
                    </span>
                    <p class="govuk-body">
                      QTS (qualified teacher status) allows you to teach in state schools in England.
                    </p>
                    <p class="govuk-body">
                      It may also allow you to teach in <a href="https://www.gov.uk/eu-eea" class="govuk-link">the EU, the EEA and Switzerland</a>. You should check with the institution you’d like to teach in for confirmation. The status of QTS in these countries may change after the UK leaves the EU. Please check <a href="https://www.gov.uk" class="govuk-link">GOV.UK</a> for updates.
                    </p>
                    <p class="govuk-body">
                      To teach in the rest of the UK or internationally, you may wish to consider a &lsquo;PGCE (or PGDE) with QTS&rsquo; qualification instead.
                    </p>
                  </label>
                </div>

                <div class="govuk-checkboxes__item">
                  <input id="applyFilter-pgce-pgde-with-qts" class="govuk-checkboxes__input" type="checkbox" name="qualification" value="@QualificationOption.PgdePgceWithQts" checked="@Model.qualifications.Contains(Enum.GetName(typeof(QualificationOption), QualificationOption.PgdePgceWithQts))" data-ga-event-form-input="PGCE / PGDE with QTS">
                  <label for="applyFilter-pgce-pgde-with-qts" class="govuk-label govuk-checkboxes__label">
                    <span class="govuk-!-font-weight-bold govuk-!-margin-bottom-2 govuk-!-display-block">
                      PGCE (or PGDE) with QTS
                    </span>
                    <p class="govuk-body">
                      A PGCE (postgraduate certificate in education) with QTS allows you
                      to teach in England, Scotland, Wales and Northern Ireland. It&rsquo;s also
                      recognised internationally. Many PGCE courses include credits that
                      count towards a Master&rsquo;s degree.
                    </p>
                    <p class="govuk-body">
                      Some providers offer a PGDE (postgraduate diploma in education) with QTS,
                      which is equivalent to a PGCE. In some cases these courses offer more
                      credits towards a Master&rsquo;s degree than PGCE courses.
                    </p>
                  </label>
                </div>

                <div class="govuk-checkboxes__item">
                  <input id="applyFilter-other" class="govuk-checkboxes__input" type="checkbox" name="qualification" value="@QualificationOption.Other" checked="@Model.qualifications.Contains(Enum.GetName(typeof(QualificationOption), QualificationOption.Other))" data-ga-event-form-input="Further Education">
                  <label for="applyFilter-other" class="govuk-label govuk-checkboxes__label">
                    <span class="govuk-!-font-weight-bold govuk-!-margin-bottom-2 govuk-!-display-block">
                      Further education (PGCE or PGDE without QTS)
                     </span>
                    <span>
                      To teach further education you don&rsquo;t need QTS. Instead you can study
                      for a PGCE or PGDE without QTS.
                    </span>
                  </label>
                </div>
              </div>
            </div>
          </fieldset>

          <div class="govuk-form-group">
            <input type="hidden" name="qualification" value="">
            <input class="govuk-button" type="submit" value="Find courses">
          </div>
        </form>
      </div>
    </div>
  </div>
</main>

src/Views/Filter/StudyType.cshtml
@model ResultsFilter

@{
  ViewBag.Title = $"Filter by study type";
}

<div class="govuk-width-container">
  @await Html.PartialAsync("Back", new BackLinkViewModel {
    Href = Url.Action("Index", "Results", Model.ToRouteValues()),
    Title = "Back to search results"
  })
</div>

<main class="govuk-main-wrapper" id="main-content" role="main">
  <div class="govuk-width-container">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <form action='@Url.Action("StudyType", "Filter", Model.ToRouteValues())' method="POST" data-ga-event-form="Study Type">
          <fieldset role="radiogroup" aria-required="true" class="govuk-fieldset">
            <legend>
              <h1 class="govuk-heading-xl">Study type</h1>
            </legend>

            <div class="govuk-form-group">
              <div class="govuk-checkboxes">
                <div class="govuk-checkboxes__item">
                  <input id="applyFilter-includefulltime" class="govuk-checkboxes__input" type="checkbox" name="fulltime" value="true" checked="@(Model.fulltime || !Model.parttime)" data-ga-event-form-input="Full time">
                  <label for="applyFilter-includefulltime" class="govuk-label govuk-checkboxes__label">
                    <span class="govuk-!-font-weight-bold govuk-!-margin-bottom-2 govuk-!-display-block">Full time (12 months)</span>
                    <span>
                      You&#8217;ll usually spend 5 days a week on a full-time course.
                    </span>
                  </label>
                </div>

                <div class="govuk-checkboxes__item">
                  <input id="applyFilter-includeparttime" class="govuk-checkboxes__input" type="checkbox" name="parttime" value="true" checked="@(Model.parttime || !Model.fulltime)" data-ga-event-form-input="Part time">
                  <label for="applyFilter-includeparttime" class="govuk-label govuk-checkboxes__label">
                    <span class="govuk-!-font-weight-bold govuk-!-margin-bottom-2 govuk-!-display-block">Part time (18 &ndash; 24 months)</span>
                    <span>
                      You&#8217;ll usually spend 3 days a week on a part-time course.
                    </span>
                  </label>
                </div>
              </div>
            </div>
          </fieldset>

          <input type="hidden" name="fulltime" value="false">
          <input type="hidden" name="parttime" value="false">

          <div class="govuk-form-group">
            <input class="govuk-button" type="submit" value="Find courses">
          </div>
        </form>
      </div>
    </div>
  </div>
</main>